apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demoapp-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      move2kube.konveyor.io/service: petstoreee7
  endpoints:
    - port: port-8080
      path: /applicationPetstore/rest/prometheus
      interval: 30s
      scrapeTimeout: 10s